/**
 * 20 scroll sections for Michael Strogoff's journey.
 * Each section defines: map camera state, narrative content, layer toggles, and atmosphere.
 */

// Route distances (cumulative km from Moscow) for progressive line reveal
const TOTAL_DISTANCE_KM = 5500;

export const sections = [
  {
    id: 'overview',
    label: 'Prologue',
    title: 'Michael Strogoff',
    subtitle: 'or, The Courier of the Czar',
    chapter: null,
    meta: '5,500 km across Russia',
    excerpt: '"A courier only could supply the place of the interrupted current. It would take this man some time to traverse the five thousand two hundred versts between Moscow and Irkutsk."',
    summary: 'In 1876, Jules Verne sent his hero on an epic journey across the vast Russian Empire — from the golden domes of Moscow to the besieged city of Irkutsk on the shores of Lake Baikal. Scroll to follow the route.',
    camera: { center: [70, 55], zoom: 2.8, pitch: 0, bearing: 0, duration: 0 },
    distanceKm: 0,
    terrain: false,
    fog: { color: '#f4f1eb', 'sky-color': '#c8dce8', 'horizon-blend': 0.08, range: [1, 12] },
    rivers: [],
    regions: [],
    isTitle: true,
  },
  {
    id: 'moscow-fete',
    label: 'Book I, Chapter I',
    title: 'A Fete at the New Palace',
    chapter: 'I.I',
    meta: 'July 15 · Moscow · 0 versts',
    excerpt: '"Beneath his eyes, bathed in moonlight, lay a fortified inclosure, from which rose two cathedrals, three palaces, and an arsenal. This river was the Moskowa; the town Moscow; the fortified inclosure the Kremlin."',
    summary: 'The Czar hosts a grand ball at the Kremlin while learning that Tartar forces under Feofar-Khan have invaded Siberia and cut all telegraph lines beyond the Urals.',
    camera: { center: [37.6177, 55.7510], zoom: 13, pitch: 30, bearing: -20, duration: 3000 },
    distanceKm: 0,
    terrain: false,
    fog: { color: '#e8e0d8', 'sky-color': '#b0a8c8', 'horizon-blend': 0.06, range: [1, 10] },
    rivers: [],
    labels: [{ text: 'Moskva River', coords: [37.6350, 55.7440] }],
    regions: [],
  },
  {
    id: 'courier-mission',
    label: 'Book I, Chapter III',
    title: "The Courier's Mission",
    chapter: 'I.III',
    meta: 'July 16 · Moscow · 0 versts',
    excerpt: '"If anyone could accomplish this journey from Moscow to Irkutsk, across a rebellious country, surmount obstacles, and brave perils of all sorts, Michael Strogoff was the man."',
    summary: 'Michael Strogoff, a captain of the Czar\'s couriers, accepts a perilous mission: carry a secret letter to the Grand Duke in Irkutsk, 5,200 versts away, through enemy-held territory.',
    camera: { center: [37.6177, 55.7510], zoom: 10, pitch: 15, bearing: 30, duration: 3000 },
    distanceKm: 0,
    terrain: false,
    fog: { color: '#ede8e0', 'sky-color': '#c0b8d0', 'horizon-blend': 0.1, range: [1, 12] },
    rivers: [],
    regions: [],
  },
  {
    id: 'train-nijni',
    label: 'Book I, Chapter IV',
    title: 'From Moscow to Nijni-Novgorod',
    chapter: 'I.IV',
    meta: 'July 16 · Moscow Station · 0 versts',
    excerpt: '"The train in which Michael took his place was to set him down at Nijni-Novgorod. It was a journey of under three hundred miles, and the train would accomplish it in ten hours."',
    summary: 'Disguised as merchant Nicholas Korpanoff, Strogoff boards the morning train. His compartment fills with Persian traders, Jewish merchants, and Cossacks — all anxiously debating the Tartar invasion\'s effect on trade. Unknown to him, two rival journalists ride the same train: Alcide Jolivet of France and Harry Blount of the Daily Telegraph.',
    camera: { center: [39.5, 56.0], zoom: 7.5, pitch: 10, bearing: 50, duration: 3000 },
    distanceKm: 0,
    terrain: false,
    fog: { color: '#eaecf0', 'sky-color': '#a8c0d8', 'horizon-blend': 0.12, range: [1, 14] },
    rivers: [],
    regions: [],
  },
  {
    id: 'vladimir-station',
    label: 'Book I, Chapter IV',
    title: 'The Station at Vladimir',
    chapter: 'I.IV',
    meta: 'July 17 · Vladimir · 190 versts',
    excerpt: '"At the station of Wladimir fresh travelers joined the train. Among others, a young girl entered the compartment occupied by Michael Strogoff."',
    summary: 'At this ancient capital of Russia, a young Livonian girl named Nadia quietly boards the train with nothing but a modest red leather bag. She takes the seat opposite Strogoff — a meeting that will change both their fates.',
    camera: { center: [40.4202, 56.1304], zoom: 12, pitch: 20, bearing: -15, duration: 3000 },
    distanceKm: 190,
    terrain: false,
    fog: { color: '#e8ecf0', 'sky-color': '#a0b8d0', 'horizon-blend': 0.12, range: [1, 14] },
    rivers: [],
    regions: [],
  },
  {
    id: 'great-fair',
    label: 'Book I, Chapter V',
    title: 'The Great Fair',
    chapter: 'I.V',
    meta: 'July 18 · Nijni-Novgorod · 440 versts',
    excerpt: '"Nijni-Novgorod, situate at the junction of the Volga and the Oka, is the chief town in the district of the same name. It was here that Michael Strogoff was obliged to leave the railway."',
    summary: 'At the confluence of the Volga and Oka rivers, the legendary trade fair teems with merchants from across Asia. But news of the Tartar invasion sends panic through the crowds.',
    camera: { center: [43.94, 56.30], zoom: 12, pitch: 25, bearing: -10, duration: 3000 },
    distanceKm: 440,
    terrain: false,
    fog: { color: '#e8ecf0', 'sky-color': '#a0b8d0', 'horizon-blend': 0.15, range: [1, 14] },
    rivers: [],
    regions: [],
  },
  {
    id: 'down-volga',
    label: 'Book I, Chapter VII',
    title: 'Down the Volga',
    chapter: 'I.VII',
    meta: 'July 19 · The Volga · 600 versts',
    excerpt: '"The Volga, the Rha of the ancients, the largest river in all Europe, is almost three thousand miles in length. The Volga forms the trunk of this tree, and it has for roots seventy mouths opening into the Caspian Sea."',
    summary: 'A steamboat carries Strogoff down the mighty Volga — Russia\'s lifeline — past wooded bluffs and scattered villages. The river fog provides cover from Tartar scouts.',
    camera: { center: [46.5, 56.0], zoom: 7, pitch: 15, bearing: 70, duration: 3000 },
    distanceKm: 600,
    terrain: false,
    fog: { color: '#e0e8f0', 'sky-color': '#98b8d8', 'horizon-blend': 0.2, range: [0.5, 10] },
    rivers: [],
    regions: [],
  },
  {
    id: 'kazan',
    label: 'Book I, Chapter VII',
    title: 'Kazan: Gate of Asia',
    chapter: 'I.VII',
    meta: 'July 20 · Kazan · 820 versts',
    excerpt: '"Kasan is justly called the \'Gate of Asia\' and considered as the center of Siberian and Bokharian commerce; for two roads begin here and lead across the Ural Mountains."',
    summary: 'At Kazan, Europe begins to give way to Asia. The great Volga bends south while Strogoff\'s route turns east up the Kama River. Tartar influence is already visible here.',
    camera: { center: [49.12, 55.79], zoom: 11, pitch: 20, bearing: 0, duration: 3000 },
    distanceKm: 820,
    terrain: false,
    fog: { color: '#f0e8e0', 'sky-color': '#d8c8a8', 'horizon-blend': 0.12, range: [1, 12] },
    rivers: ['kama'],
    regions: [],
  },
  {
    id: 'kama-perm',
    label: 'Book I, Chapter VIII',
    title: 'Up the Kama to Perm',
    chapter: 'I.VIII',
    meta: 'July 22 · Kama River · 1,400 versts',
    excerpt: '"The Kama was here very wide, and its wooded banks lovely. A few white sails enlivened the sparkling water. The horizon was closed by a line of hills covered with aspens, alders, and sometimes large oaks."',
    summary: 'The steamboat fights upstream against the Kama\'s current, passing ever-thickening forests. Beyond Perm lie the Ural Mountains — the great wall between Europe and Asia.',
    camera: { center: [54.5, 57.5], zoom: 7, pitch: 20, bearing: 45, duration: 3000 },
    distanceKm: 1400,
    terrain: false,
    fog: { color: '#e8f0e8', 'sky-color': '#a8c8a8', 'horizon-blend': 0.15, range: [1, 12] },
    rivers: ['kama'],
    regions: [],
  },
  {
    id: 'ural-storm',
    label: 'Book I, Chapter X',
    title: 'Storm in the Ural Mountains',
    chapter: 'I.X',
    meta: 'July 24 · Ural Mountains · 1,600 versts',
    excerpt: '"The Ural Mountains extend in a length of over two thousand miles between Europe and Asia. The calmness of the atmosphere was very threatening, the air being perfectly still."',
    summary: 'A violent storm breaks over the mountain pass as Strogoff crosses from Europe into Asia. Thunder echoes off granite peaks. The tarantass lurches through mud and darkness.',
    camera: { center: [58.5, 57.5], zoom: 8, pitch: 50, bearing: 30, duration: 3500 },
    distanceKm: 1600,
    terrain: true,
    fog: { color: '#d8d8e0', 'sky-color': '#8888a8', 'horizon-blend': 0.3, range: [0.3, 8] },
    rivers: [],
    regions: ['urals'],
  },
  {
    id: 'ekaterinburg',
    label: 'Book I, Chapter XI',
    title: 'Ekaterinburg: Europe Meets Asia',
    chapter: 'I.XI',
    meta: 'July 25 · Ekaterinburg · 1,800 versts',
    excerpt: '"Ekaterenburg is an Asiatic city; for it is situated beyond the Ural Mountains, on the farthest eastern slopes of the chain. Nevertheless, it belongs to the government of Perm."',
    summary: 'On the eastern slopes of the Urals, Strogoff passes the pillar marking Asia\'s border. The landscape opens into vast, flat steppes that will stretch for thousands of versts.',
    camera: { center: [60.61, 56.84], zoom: 11, pitch: 20, bearing: 60, duration: 3000 },
    distanceKm: 1800,
    terrain: true,
    fog: { color: '#e8ecf0', 'sky-color': '#a0b8d8', 'horizon-blend': 0.12, range: [1, 14] },
    rivers: [],
    regions: ['urals'],
  },
  {
    id: 'siberian-steppe',
    label: 'Book I, Chapters XII–XIII',
    title: 'The Siberian Steppe',
    chapter: 'I.XII',
    meta: 'July 27 · Tyumen to Ishim · 2,300 versts',
    excerpt: '"The steppe! For several hundred versts the ground stretched away flat and uniform. Not a tree, not a hillock, not a mound broke the monotony of this immense plain."',
    summary: 'Endless grasslands swallow the horizon. Strogoff races through Tyumen and Ishim, changing horses at relay posts, pushing east at breakneck speed while Tartar columns converge from the south.',
    camera: { center: [67.3, 56.6], zoom: 5.5, pitch: 5, bearing: 80, duration: 3500 },
    distanceKm: 2300,
    terrain: false,
    fog: { color: '#eef0ea', 'sky-color': '#c8d8c0', 'horizon-blend': 0.25, range: [1, 16] },
    rivers: [],
    regions: [],
  },
  {
    id: 'omsk',
    label: 'Book I, Chapter XIV',
    title: 'Omsk: Mother and Son',
    chapter: 'I.XIV',
    meta: 'August 1 · Omsk · 2,800 versts',
    excerpt: '"Omsk is the official capital of Western Siberia. It is at Omsk that the Governor-General of this the first half of Asiatic Russia resides."',
    summary: 'In occupied Omsk, Strogoff encounters his mother Marfa — but cannot reveal himself, as Tartar spies watch for the Czar\'s courier. He must walk past her without a word of recognition.',
    camera: { center: [73.32, 54.99], zoom: 11, pitch: 15, bearing: 0, duration: 3000 },
    distanceKm: 2800,
    terrain: false,
    fog: { color: '#ece4e0', 'sky-color': '#c8a8a0', 'horizon-blend': 0.1, range: [1, 12] },
    rivers: ['irtysh'],
    regions: [],
  },
  {
    id: 'baraba-marshes',
    label: 'Book I, Chapter XV',
    title: 'The Marshes of the Baraba',
    chapter: 'I.XV',
    meta: 'August 4 · Baraba Steppe · 3,000 versts',
    excerpt: '"These vast marshes of the Baraba form the reservoir to all the rain-water which finds no outlet either towards the Obi or towards the Irtych. The sun draws poisonous exhalations from the midst of ponds, pools, lakes, and swamps."',
    summary: 'The dreaded Baraba marshlands — a fever-ridden wasteland of bogs, mosquitoes, and treacherous footing. Horses sink to their knees. Progress slows to a crawl as Strogoff pushes on.',
    camera: { center: [78.0, 55.5], zoom: 7, pitch: 10, bearing: 70, duration: 3000 },
    distanceKm: 3000,
    terrain: false,
    fog: { color: '#e0e8de', 'sky-color': '#98b090', 'horizon-blend': 0.3, range: [0.3, 8] },
    rivers: [],
    regions: ['baraba'],
  },
  {
    id: 'kolyvan-capture',
    label: 'Book I, Chapters XVI–XVII',
    title: 'Capture at Kolyvan',
    chapter: 'I.XVI',
    meta: 'August 7 · Kolyvan · 3,200 versts',
    excerpt: '"The fields, trodden down by horses\' hoofs, afforded but too clear evidence that their hordes had passed that way. Of these barbarians it might be said: \'Where the Turk goes, no grass grows.\'"',
    summary: 'Near Kolyvan, Tartar cavalry overtakes Strogoff. He is captured along with Nadia, Blount, and Jolivet, and brought before the traitor Ivan Ogareff and the Tartar Khan, Feofar.',
    camera: { center: [82.53, 55.31], zoom: 10, pitch: 15, bearing: -20, duration: 3000 },
    distanceKm: 3200,
    terrain: false,
    fog: { color: '#ece0d0', 'sky-color': '#c8b090', 'horizon-blend': 0.2, range: [0.5, 10] },
    rivers: [],
    regions: [],
  },
  {
    id: 'tomsk',
    label: 'Book II, Chapters III–IV',
    title: 'Tomsk: The Tartar Camp',
    chapter: 'II.III',
    meta: 'August 12 · Tomsk · 3,600 versts',
    excerpt: '"Tomsk, founded in 1604, nearly in the heart of the Siberian provinces, is one of the most important towns in Asiatic Russia. It is a city of millionaires, enriched by the spade and pickax."',
    summary: 'Tomsk has become the seat of Feofar-Khan\'s power. The once-prosperous city is now a military camp. Strogoff is brought before the Khan for judgment.',
    camera: { center: [84.97, 56.50], zoom: 11, pitch: 15, bearing: 10, duration: 3000 },
    distanceKm: 3600,
    terrain: false,
    fog: { color: '#f0dcd0', 'sky-color': '#c89080', 'horizon-blend': 0.1, range: [1, 12] },
    rivers: [],
    regions: [],
  },
  {
    id: 'blinding',
    label: 'Book II, Chapter V',
    title: 'The Blinding',
    chapter: 'II.V',
    meta: 'August 15 · Tomsk · 3,600 versts',
    excerpt: '"Look while you may!" cried Ivan Ogareff. The incandescent blade passed before Michael\'s eyes. A despairing cry was heard. His aged mother fell senseless to the ground. Michael Strogoff was blind.',
    summary: 'In the cruelest act of the journey, the traitor Ogareff orders Strogoff blinded with a white-hot saber. But tears — shed for his mother — save his sight, a secret he must guard with his life.',
    camera: { center: [84.97, 56.50], zoom: 13.5, pitch: 10, bearing: 0, duration: 2500 },
    distanceKm: 3600,
    terrain: false,
    fog: { color: '#f0c8c0', 'sky-color': '#c07060', 'horizon-blend': 0.05, range: [0.5, 6] },
    rivers: [],
    regions: [],
  },
  {
    id: 'krasnoyarsk',
    label: 'Book II, Chapter VII',
    title: 'The Passage of the Yenisei',
    chapter: 'II.VII',
    meta: 'August 25 · Krasnoyarsk · 4,100 versts',
    excerpt: '"At this place the Yenisei is not less than a mile in width, and forms two arms. Between these arms lie several islands, covered with alders, willows, and poplars, looking like verdant ships, anchored in the river."',
    summary: 'Freed but presumed blind, Strogoff and Nadia push east. At Krasnoyarsk they must cross the mighty Yenisei — Siberia\'s greatest river — through a city devastated by the Tartar advance.',
    camera: { center: [92.89, 56.02], zoom: 10, pitch: 15, bearing: -30, duration: 3000 },
    distanceKm: 4100,
    terrain: false,
    fog: { color: '#e0e0e8', 'sky-color': '#a0a0b8', 'horizon-blend': 0.15, range: [1, 12] },
    rivers: ['yenisei'],
    regions: [],
  },
  {
    id: 'baikal',
    label: 'Book II, Chapter X',
    title: 'Lake Baikal',
    chapter: 'II.X',
    meta: 'September 20 · Lake Baikal · 5,100 versts',
    excerpt: '"Lake Baikal is situated seventeen hundred feet above the level of the sea. Its length is about six hundred miles, its breadth seventy. This immense basin of fresh water, fed by more than three hundred rivers, is surrounded by magnificent volcanic mountains."',
    summary: 'The "Pearl of Siberia" — the deepest lake on Earth, ringed by volcanic mountains and dark forests. Strogoff must cross its frozen waters, the final great barrier before Irkutsk.',
    camera: { center: [108.17, 53.56], zoom: 7.5, pitch: 45, bearing: -40, duration: 3500 },
    distanceKm: 5100,
    terrain: true,
    fog: { color: '#d8e8f0', 'sky-color': '#6098c0', 'horizon-blend': 0.15, range: [0.5, 10] },
    rivers: [],
    regions: ['baikal'],
  },
  {
    id: 'angara',
    label: 'Book II, Chapters X–XI',
    title: 'The Angara to Irkutsk',
    chapter: 'II.X',
    meta: 'October 2 · Angara River · 5,150 versts',
    excerpt: '"A moving panorama was displayed on both sides of the river. Here were high granite cliffs, there wild gorges, down which rushed a torrent; sometimes appeared a clearing with a still smoking village, then thick pine forests blazing."',
    summary: 'The Angara River — Baikal\'s only outlet — carries Strogoff on a raft of ice toward Irkutsk. The cold is brutal. Ice floes crash and grind. But the city lights finally appear on the horizon.',
    camera: { center: [106.2, 52.9], zoom: 9, pitch: 25, bearing: -60, duration: 3000 },
    distanceKm: 5150,
    terrain: true,
    fog: { color: '#dce8f0', 'sky-color': '#78a8c8', 'horizon-blend': 0.2, range: [0.5, 10] },
    rivers: ['angara'],
    regions: ['baikal'],
  },
  {
    id: 'irkutsk',
    label: 'Book II, Chapters XII–XIV',
    title: 'Irkutsk: Siege and Victory',
    chapter: 'II.XII',
    meta: 'October 5 · Irkutsk · 5,200 versts',
    excerpt: '"Irkutsk, the capital of Eastern Siberia, is a populous town. With its cupolas, its bell-towers, its steeples slender as minarets, its domes like pot-bellied Chinese jars, it presents something of an oriental aspect."',
    summary: 'Irkutsk is under siege. Strogoff delivers the Czar\'s letter, unmasks the traitor Ogareff in single combat, and reveals his sight. The city is saved. The courier\'s mission is complete.',
    camera: { center: [104.31, 52.29], zoom: 12, pitch: 20, bearing: 10, duration: 3000 },
    distanceKm: 5200,
    terrain: false,
    fog: { color: '#f0e8d8', 'sky-color': '#d8b878', 'horizon-blend': 0.1, range: [1, 12] },
    rivers: ['angara'],
    regions: [],
    isConclusion: true,
  },
];

export { TOTAL_DISTANCE_KM };
